config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'articles#index'
  resources :articles do
		resources :comments

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, :dependent => :destroy

	validates :title, presence: true
	validates :body, presence: true
	def self.search(search)
		where("title || body ILIKE ?", "%#{search}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

def index
	@articles = Article.all
	@articles = Article.paginate(:page => params[:page], per_page: 2)
	@markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)

    if params[:search]
     @articles = @articles.search(params[:search])
   else
    @articles = Article.all
  end
  @articles = @articles.order("created_at DESC").paginate(:page => params[:page], per_page: 2)
end


def new 
	@article = Article.new
end

def create
	@article = current_user.articles.create(article_params)
  if @article.valid?
    redirect_to root_path
  else
    render :new, status: :unprocessable_entity
  end
 end

 def show
 	@article = Article.find(params[:id])
 	@comment = Comment.new
 end

 def edit
 	@article = Article.find(params[:id])

 	if @article.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end
 end


 def update
 	@article = Article.find(params[:id])

 	if @article.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end


 	@article.update_attributes(article_params)
 	if @article.valid?
    redirect_to root_path
  else
    render :edit, status: :unprocessable_entity
  end
 end

 def destroy
 	 @article = Article.find(params[:id])
 	 if @article.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end


 	 @article.destroy
 	 redirect_to root_path
 end

 private

 def article_params
 	params.require(:article).permit(:title, :body)
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

def index
end	

def new
  @comments = Comment.new(params[:id])
  end

def create
	@article = Article.find(params[:article_id])
	@article.comments.create(comment_params.merge(user: current_user))
	redirect_to article_path(@article)
 end

 def edit
  article = Article.find(params[:article_id])
  @comment = article.comments.find(params[:id])
 end

 def show
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id])
 end


 def update
  @article = Article.find(params[:article_id])
  @comment = @article.comments.find(params[:id]) 
 	if @comment.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end


 	@comment.update_attributes(comment_params)
 	if @comment.valid?
    redirect_to root_path
  else
    render :edit, status: :unprocessable_entity
  end
 end


 def destroy
  @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  if @comment.article.user != current_user
    return render text: 'Not Allowed', status: :forbidden
  end

  @comment.destroy
  redirect_to root_path
 end

 private

  def comment_params
    params.require(:comment).permit(:message)
  end

  def find_article
	@article = Article.find(params[:article_id])
end

  def find_comment
	comment = @article.comments.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Article</h1>
  <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<div class="booyah-box col-10 offset-1">
		<h1><%= link_to article.title, article_path(article) %></h1>
	    <i><%= @markdown.render(article.body).html_safe  %></i><br /><br />
	   
        <h4>When: <%= time_ago_in_words(article.created_at) %></h4>
      
        

        <% if article.user.present? %>
      <small><%= article.user.email %></small>
    <% end %>
        
  </div>

  
<% end %>


<div class="pagination col-xs-10 col-xs-offset-1">
      <p><%= will_paginate @articles, previous_label: "Older", next_label: "Newer", renderer: BootstrapPagination::Rails %></p>
</div>

app/views/articles/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Article Details</h1>
  <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="booyah-box col-10 offset-1">
	<h1><%= @article.title %></h1>
	<i><%= @article.body %></i>
	<br /><br />
  <div class="float-right" style="margin-bottom: 15px">
  <% if user_signed_in? %>
  	<% if current_user && current_user == @article.user %>
    	<%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary' %>
    	<%= link_to 'Destroy', article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    	</div>
    <% end %>
</div>
<% end %>


<div class="booyah-box col-10 offset-1">
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= simple_form_for @comment, url: article_comments_path(@article) do |f| %>
  <%= f.input :message %>
  <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
<% end %>
</div>


<% @article.comments.each do |comment| %>
  <div class="booyah-box col-10 offset-1">
    <blockquote>
      <b><%= comment.message %></b> - 
      <small><%= comment.user.email %></small>
    </blockquote>
    <br /><br />
  	<% if current_user && current_user == comment.user %>
    	<%= link_to 'Edit', edit_article_comment_path(comment.article_id, comment.id), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', article_comment_path(comment.article, comment.id), method: :delete, class: 'btn btn-danger' %>
    <% end %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="booyah-box col-10 offset-1">
<%= simple_form_for @comment, url: article_comment_path(@comment, :article_id => @comment.article_id)  do |f| %>
  <%= f.input :message %>
  <br />
  <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Blogster', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_article_path, class: 'nav-link' do %>
            <i class="fa fa-plus-circle">New Article</i>
            <% end %>
          </li>
          </ul>
     <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
      		<%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    	</li>
      <% end %>
    </ul>
        <form class="form-inline my-2 my-lg-0">
          <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
		  <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
		  <%= submit_tag "Search" %>
		  <% end %>
        </form>
      </div>
    </nav>


	<% if notice.present? %>
	  <p class="alert alert-info"><%= notice %></p>
	<% end %>
	<% if alert.present? %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
    

    	<%= yield %>

   
     <br class="clr" />





    
  </body>
</html>